// AUTO-GENERATED by examples/wander/gen-assets.ts — grow's committed art,
// referenced in place ("../grow/assets/..." resolves against an importing
// example's directory at build time), plus shared whole-stamp and 64 px fill
// composites under "../wander/assets/...". Full literals let tools/build.ts
// bake them without copying art into each importing example.

/** [biome][seam kind]: fill, transition, blend, fringe (16 px). */
export const WANDER_TERRAIN: readonly (readonly string[])[] = [
  ["../grow/assets/grow-terrain-0-fill.png", "../grow/assets/grow-terrain-0-transition.png", "../grow/assets/grow-terrain-0-blend.png", "../grow/assets/grow-terrain-0-fringe.png"],
  ["../grow/assets/grow-terrain-1-fill.png", "../grow/assets/grow-terrain-1-transition.png", "../grow/assets/grow-terrain-1-blend.png", "../grow/assets/grow-terrain-1-fringe.png"],
  ["../grow/assets/grow-terrain-2-fill.png", "../grow/assets/grow-terrain-2-transition.png", "../grow/assets/grow-terrain-2-blend.png", "../grow/assets/grow-terrain-2-fringe.png"],
  ["../grow/assets/grow-terrain-3-fill.png", "../grow/assets/grow-terrain-3-transition.png", "../grow/assets/grow-terrain-3-blend.png", "../grow/assets/grow-terrain-3-fringe.png"],
];

/** 256 px biome fill blocks (16 x 16 tiles). */
export const WANDER_BLOCK: readonly string[] = [
  "../grow/assets/grow-terrain-0-block.png",
  "../grow/assets/grow-terrain-1-block.png",
  "../grow/assets/grow-terrain-2-block.png",
  "../grow/assets/grow-terrain-3-block.png",
];

/** 64 px biome fills (4 x 4 tiles). */
export const WANDER_FILL64: readonly string[] = [
  "../wander/assets/fill64-0.png",
  "../wander/assets/fill64-1.png",
  "../wander/assets/fill64-2.png",
  "../wander/assets/fill64-3.png",
];

/** Developed ground cells by GROW_TILE id (16 px). */
export const WANDER_GROUND: readonly (string | null)[] = [
  null, "../grow/assets/grow-ground-1.png", "../grow/assets/grow-ground-2.png", "../grow/assets/grow-ground-3.png",
  "../grow/assets/grow-ground-4.png", "../grow/assets/grow-ground-5.png", "../grow/assets/grow-ground-6.png", "../grow/assets/grow-ground-7.png",
  "../grow/assets/grow-ground-8.png", "../grow/assets/grow-ground-9.png", "../grow/assets/grow-ground-10.png", "../grow/assets/grow-ground-11.png",
  "../grow/assets/grow-ground-12.png", "../grow/assets/grow-ground-13.png", "../grow/assets/grow-ground-14.png", "../grow/assets/grow-ground-15.png",
  "../grow/assets/grow-ground-16.png",
];

/** Upper cells (props, houses, Ninja stamps) by cell id (16 px). */
export const WANDER_UPPER: readonly (string | null)[] = [
  null, null, null, null,
  null, null, null, null,
  null, null, null, null,
  null, null, null, null,
  null, null, null, null,
  "../grow/assets/grow-upper-20.png", "../grow/assets/grow-upper-21.png", "../grow/assets/grow-upper-22.png", "../grow/assets/grow-upper-23.png",
  "../grow/assets/grow-upper-24.png", "../grow/assets/grow-upper-25.png", "../grow/assets/grow-upper-26.png", "../grow/assets/grow-upper-27.png",
  "../grow/assets/grow-upper-28.png", "../grow/assets/grow-upper-29.png", "../grow/assets/grow-upper-30.png", "../grow/assets/grow-upper-31.png",
  "../grow/assets/grow-upper-32.png", "../grow/assets/grow-upper-33.png", "../grow/assets/grow-upper-34.png", "../grow/assets/grow-upper-35.png",
  "../grow/assets/grow-upper-36.png", "../grow/assets/grow-upper-37.png", "../grow/assets/grow-upper-38.png", "../grow/assets/grow-upper-39.png",
  "../grow/assets/grow-upper-40.png", "../grow/assets/grow-upper-41.png", "../grow/assets/grow-upper-42.png", "../grow/assets/grow-upper-43.png",
  "../grow/assets/grow-upper-44.png", "../grow/assets/grow-upper-45.png", "../grow/assets/grow-upper-46.png", "../grow/assets/grow-upper-47.png",
  "../grow/assets/grow-upper-48.png", "../grow/assets/grow-upper-49.png", "../grow/assets/grow-upper-50.png", "../grow/assets/grow-upper-51.png",
  "../grow/assets/grow-upper-52.png", "../grow/assets/grow-upper-53.png", "../grow/assets/grow-upper-54.png", "../grow/assets/grow-upper-55.png",
  "../grow/assets/grow-upper-56.png", "../grow/assets/grow-upper-57.png", "../grow/assets/grow-upper-58.png", "../grow/assets/grow-upper-59.png",
  "../grow/assets/grow-upper-60.png", "../grow/assets/grow-upper-61.png", "../grow/assets/grow-upper-62.png", "../grow/assets/grow-upper-63.png",
  "../grow/assets/grow-upper-64.png", "../grow/assets/grow-upper-65.png", "../grow/assets/grow-upper-66.png", "../grow/assets/grow-upper-67.png",
  "../grow/assets/grow-upper-68.png", "../grow/assets/grow-upper-69.png", "../grow/assets/grow-upper-70.png", "../grow/assets/grow-upper-71.png",
  "../grow/assets/grow-upper-72.png", "../grow/assets/grow-upper-73.png", "../grow/assets/grow-upper-74.png", "../grow/assets/grow-upper-75.png",
  "../grow/assets/grow-upper-76.png", "../grow/assets/grow-upper-77.png", "../grow/assets/grow-upper-78.png", null,
  null, null, null, null,
  null, null, null, null,
  null, null, null, null,
  null, null, null, null,
  null, null, null, null,
  null, null, null, null,
  null, null, null, null,
  null, null, null, null,
  null, null, null, null,
  null, null, null, null,
  null, null, null, null,
  null, null, null, null,
  "../grow/assets/grow-upper-128.png", "../grow/assets/grow-upper-129.png", "../grow/assets/grow-upper-130.png", "../grow/assets/grow-upper-131.png",
  "../grow/assets/grow-upper-132.png", "../grow/assets/grow-upper-133.png", "../grow/assets/grow-upper-134.png", "../grow/assets/grow-upper-135.png",
  "../grow/assets/grow-upper-136.png", "../grow/assets/grow-upper-137.png", "../grow/assets/grow-upper-138.png", "../grow/assets/grow-upper-139.png",
  "../grow/assets/grow-upper-140.png", "../grow/assets/grow-upper-141.png", "../grow/assets/grow-upper-142.png", "../grow/assets/grow-upper-143.png",
  "../grow/assets/grow-upper-144.png", "../grow/assets/grow-upper-145.png", "../grow/assets/grow-upper-146.png", "../grow/assets/grow-upper-147.png",
  "../grow/assets/grow-upper-148.png", "../grow/assets/grow-upper-149.png", "../grow/assets/grow-upper-150.png", "../grow/assets/grow-upper-151.png",
  "../grow/assets/grow-upper-152.png", "../grow/assets/grow-upper-153.png", "../grow/assets/grow-upper-154.png", "../grow/assets/grow-upper-155.png",
  "../grow/assets/grow-upper-156.png", "../grow/assets/grow-upper-157.png", "../grow/assets/grow-upper-158.png", "../grow/assets/grow-upper-159.png",
  "../grow/assets/grow-upper-160.png", "../grow/assets/grow-upper-161.png", "../grow/assets/grow-upper-162.png", "../grow/assets/grow-upper-163.png",
  "../grow/assets/grow-upper-164.png", "../grow/assets/grow-upper-165.png", "../grow/assets/grow-upper-166.png", "../grow/assets/grow-upper-167.png",
  "../grow/assets/grow-upper-168.png", "../grow/assets/grow-upper-169.png", "../grow/assets/grow-upper-170.png", "../grow/assets/grow-upper-171.png",
  "../grow/assets/grow-upper-172.png", "../grow/assets/grow-upper-173.png", "../grow/assets/grow-upper-174.png", "../grow/assets/grow-upper-175.png",
  "../grow/assets/grow-upper-176.png", "../grow/assets/grow-upper-177.png", "../grow/assets/grow-upper-178.png", "../grow/assets/grow-upper-179.png",
  "../grow/assets/grow-upper-180.png", "../grow/assets/grow-upper-181.png", "../grow/assets/grow-upper-182.png", "../grow/assets/grow-upper-183.png",
  "../grow/assets/grow-upper-184.png", "../grow/assets/grow-upper-185.png", "../grow/assets/grow-upper-186.png", "../grow/assets/grow-upper-187.png",
  "../grow/assets/grow-upper-188.png", "../grow/assets/grow-upper-189.png", "../grow/assets/grow-upper-190.png", "../grow/assets/grow-upper-191.png",
  "../grow/assets/grow-upper-192.png", "../grow/assets/grow-upper-193.png", "../grow/assets/grow-upper-194.png", "../grow/assets/grow-upper-195.png",
  "../grow/assets/grow-upper-196.png", "../grow/assets/grow-upper-197.png", "../grow/assets/grow-upper-198.png", "../grow/assets/grow-upper-199.png",
  "../grow/assets/grow-upper-200.png", "../grow/assets/grow-upper-201.png", "../grow/assets/grow-upper-202.png", "../grow/assets/grow-upper-203.png",
  "../grow/assets/grow-upper-204.png", "../grow/assets/grow-upper-205.png", "../grow/assets/grow-upper-206.png", "../grow/assets/grow-upper-207.png",
  "../grow/assets/grow-upper-208.png", "../grow/assets/grow-upper-209.png", "../grow/assets/grow-upper-210.png", "../grow/assets/grow-upper-211.png",
  "../grow/assets/grow-upper-212.png", "../grow/assets/grow-upper-213.png", "../grow/assets/grow-upper-214.png", "../grow/assets/grow-upper-215.png",
  "../grow/assets/grow-upper-216.png", "../grow/assets/grow-upper-217.png", "../grow/assets/grow-upper-218.png", "../grow/assets/grow-upper-219.png",
  "../grow/assets/grow-upper-220.png", "../grow/assets/grow-upper-221.png", "../grow/assets/grow-upper-222.png", "../grow/assets/grow-upper-223.png",
  "../grow/assets/grow-upper-224.png", "../grow/assets/grow-upper-225.png", "../grow/assets/grow-upper-226.png", "../grow/assets/grow-upper-227.png",
  "../grow/assets/grow-upper-228.png", "../grow/assets/grow-upper-229.png", "../grow/assets/grow-upper-230.png", "../grow/assets/grow-upper-231.png",
  "../grow/assets/grow-upper-232.png", "../grow/assets/grow-upper-233.png", "../grow/assets/grow-upper-234.png", "../grow/assets/grow-upper-235.png",
  "../grow/assets/grow-upper-236.png", "../grow/assets/grow-upper-237.png", "../grow/assets/grow-upper-238.png", "../grow/assets/grow-upper-239.png",
  "../grow/assets/grow-upper-240.png", "../grow/assets/grow-upper-241.png", "../grow/assets/grow-upper-242.png", "../grow/assets/grow-upper-243.png",
  "../grow/assets/grow-upper-244.png", "../grow/assets/grow-upper-245.png", "../grow/assets/grow-upper-246.png", "../grow/assets/grow-upper-247.png",
  "../grow/assets/grow-upper-248.png", "../grow/assets/grow-upper-249.png", "../grow/assets/grow-upper-250.png", "../grow/assets/grow-upper-251.png",
  "../grow/assets/grow-upper-252.png", "../grow/assets/grow-upper-253.png", "../grow/assets/grow-upper-254.png", "../grow/assets/grow-upper-255.png",
  "../grow/assets/grow-upper-256.png", "../grow/assets/grow-upper-257.png", "../grow/assets/grow-upper-258.png", "../grow/assets/grow-upper-259.png",
  "../grow/assets/grow-upper-260.png", "../grow/assets/grow-upper-261.png", "../grow/assets/grow-upper-262.png", "../grow/assets/grow-upper-263.png",
  "../grow/assets/grow-upper-264.png", "../grow/assets/grow-upper-265.png", "../grow/assets/grow-upper-266.png", "../grow/assets/grow-upper-267.png",
  "../grow/assets/grow-upper-268.png", "../grow/assets/grow-upper-269.png", "../grow/assets/grow-upper-270.png", "../grow/assets/grow-upper-271.png",
  "../grow/assets/grow-upper-272.png", "../grow/assets/grow-upper-273.png", "../grow/assets/grow-upper-274.png", "../grow/assets/grow-upper-275.png",
  "../grow/assets/grow-upper-276.png", "../grow/assets/grow-upper-277.png", "../grow/assets/grow-upper-278.png", "../grow/assets/grow-upper-279.png",
  "../grow/assets/grow-upper-280.png", "../grow/assets/grow-upper-281.png", "../grow/assets/grow-upper-282.png", "../grow/assets/grow-upper-283.png",
  "../grow/assets/grow-upper-284.png", "../grow/assets/grow-upper-285.png", "../grow/assets/grow-upper-286.png", "../grow/assets/grow-upper-287.png",
  "../grow/assets/grow-upper-288.png", "../grow/assets/grow-upper-289.png", "../grow/assets/grow-upper-290.png", "../grow/assets/grow-upper-291.png",
  "../grow/assets/grow-upper-292.png", "../grow/assets/grow-upper-293.png", "../grow/assets/grow-upper-294.png", "../grow/assets/grow-upper-295.png",
  "../grow/assets/grow-upper-296.png", "../grow/assets/grow-upper-297.png", "../grow/assets/grow-upper-298.png", "../grow/assets/grow-upper-299.png",
  "../grow/assets/grow-upper-300.png", "../grow/assets/grow-upper-301.png", "../grow/assets/grow-upper-302.png", "../grow/assets/grow-upper-303.png",
  "../grow/assets/grow-upper-304.png", "../grow/assets/grow-upper-305.png", "../grow/assets/grow-upper-306.png", "../grow/assets/grow-upper-307.png",
  "../grow/assets/grow-upper-308.png", "../grow/assets/grow-upper-309.png", "../grow/assets/grow-upper-310.png", "../grow/assets/grow-upper-311.png",
  "../grow/assets/grow-upper-312.png", "../grow/assets/grow-upper-313.png", "../grow/assets/grow-upper-314.png", "../grow/assets/grow-upper-315.png",
  "../grow/assets/grow-upper-316.png", "../grow/assets/grow-upper-317.png", "../grow/assets/grow-upper-318.png", "../grow/assets/grow-upper-319.png",
  "../grow/assets/grow-upper-320.png", "../grow/assets/grow-upper-321.png", "../grow/assets/grow-upper-322.png", "../grow/assets/grow-upper-323.png",
  "../grow/assets/grow-upper-324.png", "../grow/assets/grow-upper-325.png", "../grow/assets/grow-upper-326.png", "../grow/assets/grow-upper-327.png",
  "../grow/assets/grow-upper-328.png", "../grow/assets/grow-upper-329.png", "../grow/assets/grow-upper-330.png", "../grow/assets/grow-upper-331.png",
  "../grow/assets/grow-upper-332.png", "../grow/assets/grow-upper-333.png", "../grow/assets/grow-upper-334.png", "../grow/assets/grow-upper-335.png",
  "../grow/assets/grow-upper-336.png", "../grow/assets/grow-upper-337.png", "../grow/assets/grow-upper-338.png", "../grow/assets/grow-upper-339.png",
  "../grow/assets/grow-upper-340.png", "../grow/assets/grow-upper-341.png", "../grow/assets/grow-upper-342.png", "../grow/assets/grow-upper-343.png",
  "../grow/assets/grow-upper-344.png", "../grow/assets/grow-upper-345.png", "../grow/assets/grow-upper-346.png", "../grow/assets/grow-upper-347.png",
  "../grow/assets/grow-upper-348.png", "../grow/assets/grow-upper-349.png", "../grow/assets/grow-upper-350.png", "../grow/assets/grow-upper-351.png",
];

/** Whole multi-cell stamps: [base cell id, image width px, image height px,
 *  image] (power-of-two images; houses are padded transparent). */
export const WANDER_STAMPS: readonly (readonly [number, number, number, string])[] = [
  [128, 32, 32, "../wander/assets/stamp-tree-round.png"],
  [132, 32, 32, "../wander/assets/stamp-tree-pine.png"],
  [136, 32, 32, "../wander/assets/stamp-tree-dead.png"],
  [140, 32, 32, "../wander/assets/stamp-tree-snowpine-moss.png"],
  [144, 32, 32, "../wander/assets/stamp-tree-snowpine.png"],
  [148, 32, 32, "../wander/assets/stamp-tree-snowround.png"],
  [152, 32, 32, "../wander/assets/stamp-tree-cherry.png"],
  [156, 32, 32, "../wander/assets/stamp-tree-round-b.png"],
  [160, 32, 32, "../wander/assets/stamp-tree-round-c.png"],
  [164, 32, 32, "../wander/assets/stamp-tree-small.png"],
  [168, 32, 32, "../wander/assets/stamp-stump-big.png"],
  [172, 32, 32, "../wander/assets/stamp-stump-big-b.png"],
  [176, 32, 32, "../wander/assets/stamp-boulder-brown.png"],
  [180, 32, 32, "../wander/assets/stamp-boulder-grey.png"],
  [184, 32, 32, "../wander/assets/stamp-bush-dark.png"],
  [188, 32, 32, "../wander/assets/stamp-bush-snow.png"],
  [212, 32, 32, "../wander/assets/stamp-palm.png"],
  [216, 32, 32, "../wander/assets/stamp-palm-b.png"],
  [222, 32, 32, "../wander/assets/stamp-market-red.png"],
  [226, 32, 32, "../wander/assets/stamp-market-gold.png"],
  [232, 64, 64, "../wander/assets/stamp-house-orange.png"],
  [244, 64, 64, "../wander/assets/stamp-house-redtile.png"],
  [256, 64, 64, "../wander/assets/stamp-house-beige.png"],
  [268, 64, 64, "../wander/assets/stamp-hut-wood.png"],
  [277, 64, 64, "../wander/assets/stamp-hut-gable.png"],
  [286, 64, 64, "../wander/assets/stamp-hut-thatch.png"],
  [295, 64, 64, "../wander/assets/stamp-dome-green.png"],
  [304, 64, 64, "../wander/assets/stamp-house-flat.png"],
  [316, 64, 64, "../wander/assets/stamp-house-round-beige.png"],
  [325, 64, 64, "../wander/assets/stamp-igloo.png"],
  [334, 64, 64, "../wander/assets/stamp-igloo-b.png"],
  [343, 64, 64, "../wander/assets/stamp-igloo-c.png"],
];

export const WANDER_VILLAGER = "../grow/assets/grow-villager.png";

// Player walker frames (Sharm "Tiny 16"), facing order 0 down, 1 left,
// 2 up, 3 right. Kept as an alternate player look; the default player look
// comes from the WANDER_LOOKS pool (see WanderView).
export const WANDER_PLAYER = {
  idle: ["../grow/assets/player-dir0.png", "../grow/assets/player-dir1.png", "../grow/assets/player-dir2.png", "../grow/assets/player-dir3.png"],
  walkL: ["../grow/assets/player-pose0-l.png", "../grow/assets/player-pose1-l.png", "../grow/assets/player-pose2-l.png", "../grow/assets/player-pose3-l.png"],
  walkR: ["../grow/assets/player-pose0-r.png", "../grow/assets/player-pose1-r.png", "../grow/assets/player-pose2-r.png", "../grow/assets/player-pose3-r.png"],
} as const;

// The character look pool: 16 Ninja Adventure walkers x
// 4 palettes = 64 looks, indexed by
// the stable id base*4+palette (see examples/wander/looks.ts).
// Each look's twelve frames are tile indices into its base's CLUT8 TILESET
// (tile = palette*12 + pose*4 + facing); the pak ships one TILESET per base,
// streamed on demand (see examples/wander/gen-assets.ts).
export const WANDER_LOOK_BASES = [
  "Villager", // 0
  "Villager2", // 1
  "Villager3", // 2
  "Villager4", // 3
  "Boy", // 4
  "Woman", // 5
  "ManGreen", // 6
  "OldMan", // 7
  "OldMan2", // 8
  "Monk", // 9
  "Monk2", // 10
  "Hunter", // 11
  "Eskimo", // 12
  "Noble", // 13
  "Samurai", // 14
  "SamuraiBlue", // 15
] as const;

export const WANDER_LOOK_PALETTES = [
  "original", // 0
  "rust", // 1
  "azure", // 2
  "forest", // 3
] as const;

export interface WanderLook {
  /** Stable published id: base * 4 + palette. Never reorder. */
  id: number;
  base: number;
  palette: number;
  name: string;
  /** TILESET pak key holding this base's 48 frames (ui:tile.wander-look-b<NN>). */
  tileset: string;
  /** Tile index per pose and facing (0 down, 1 left, 2 up, 3 right):
   *  palette*12 + pose*4 + facing. */
  frames: {
    idle: readonly [number, number, number, number];
    walkL: readonly [number, number, number, number];
    walkR: readonly [number, number, number, number];
  };
  /** Tile index of the down-facing idle frame, for the create-character scene and ROSTER. */
  thumb: number;
}

export const WANDER_LOOKS: readonly WanderLook[] = [
  { id: 0, base: 0, palette: 0, name: "Villager", tileset: "ui:tile.wander-look-b00", frames: { idle: [0, 1, 2, 3], walkL: [4, 5, 6, 7], walkR: [8, 9, 10, 11] }, thumb: 0 },
  { id: 1, base: 0, palette: 1, name: "Villager", tileset: "ui:tile.wander-look-b00", frames: { idle: [12, 13, 14, 15], walkL: [16, 17, 18, 19], walkR: [20, 21, 22, 23] }, thumb: 12 },
  { id: 2, base: 0, palette: 2, name: "Villager", tileset: "ui:tile.wander-look-b00", frames: { idle: [24, 25, 26, 27], walkL: [28, 29, 30, 31], walkR: [32, 33, 34, 35] }, thumb: 24 },
  { id: 3, base: 0, palette: 3, name: "Villager", tileset: "ui:tile.wander-look-b00", frames: { idle: [36, 37, 38, 39], walkL: [40, 41, 42, 43], walkR: [44, 45, 46, 47] }, thumb: 36 },
  { id: 4, base: 1, palette: 0, name: "Villager2", tileset: "ui:tile.wander-look-b01", frames: { idle: [0, 1, 2, 3], walkL: [4, 5, 6, 7], walkR: [8, 9, 10, 11] }, thumb: 0 },
  { id: 5, base: 1, palette: 1, name: "Villager2", tileset: "ui:tile.wander-look-b01", frames: { idle: [12, 13, 14, 15], walkL: [16, 17, 18, 19], walkR: [20, 21, 22, 23] }, thumb: 12 },
  { id: 6, base: 1, palette: 2, name: "Villager2", tileset: "ui:tile.wander-look-b01", frames: { idle: [24, 25, 26, 27], walkL: [28, 29, 30, 31], walkR: [32, 33, 34, 35] }, thumb: 24 },
  { id: 7, base: 1, palette: 3, name: "Villager2", tileset: "ui:tile.wander-look-b01", frames: { idle: [36, 37, 38, 39], walkL: [40, 41, 42, 43], walkR: [44, 45, 46, 47] }, thumb: 36 },
  { id: 8, base: 2, palette: 0, name: "Villager3", tileset: "ui:tile.wander-look-b02", frames: { idle: [0, 1, 2, 3], walkL: [4, 5, 6, 7], walkR: [8, 9, 10, 11] }, thumb: 0 },
  { id: 9, base: 2, palette: 1, name: "Villager3", tileset: "ui:tile.wander-look-b02", frames: { idle: [12, 13, 14, 15], walkL: [16, 17, 18, 19], walkR: [20, 21, 22, 23] }, thumb: 12 },
  { id: 10, base: 2, palette: 2, name: "Villager3", tileset: "ui:tile.wander-look-b02", frames: { idle: [24, 25, 26, 27], walkL: [28, 29, 30, 31], walkR: [32, 33, 34, 35] }, thumb: 24 },
  { id: 11, base: 2, palette: 3, name: "Villager3", tileset: "ui:tile.wander-look-b02", frames: { idle: [36, 37, 38, 39], walkL: [40, 41, 42, 43], walkR: [44, 45, 46, 47] }, thumb: 36 },
  { id: 12, base: 3, palette: 0, name: "Villager4", tileset: "ui:tile.wander-look-b03", frames: { idle: [0, 1, 2, 3], walkL: [4, 5, 6, 7], walkR: [8, 9, 10, 11] }, thumb: 0 },
  { id: 13, base: 3, palette: 1, name: "Villager4", tileset: "ui:tile.wander-look-b03", frames: { idle: [12, 13, 14, 15], walkL: [16, 17, 18, 19], walkR: [20, 21, 22, 23] }, thumb: 12 },
  { id: 14, base: 3, palette: 2, name: "Villager4", tileset: "ui:tile.wander-look-b03", frames: { idle: [24, 25, 26, 27], walkL: [28, 29, 30, 31], walkR: [32, 33, 34, 35] }, thumb: 24 },
  { id: 15, base: 3, palette: 3, name: "Villager4", tileset: "ui:tile.wander-look-b03", frames: { idle: [36, 37, 38, 39], walkL: [40, 41, 42, 43], walkR: [44, 45, 46, 47] }, thumb: 36 },
  { id: 16, base: 4, palette: 0, name: "Boy", tileset: "ui:tile.wander-look-b04", frames: { idle: [0, 1, 2, 3], walkL: [4, 5, 6, 7], walkR: [8, 9, 10, 11] }, thumb: 0 },
  { id: 17, base: 4, palette: 1, name: "Boy", tileset: "ui:tile.wander-look-b04", frames: { idle: [12, 13, 14, 15], walkL: [16, 17, 18, 19], walkR: [20, 21, 22, 23] }, thumb: 12 },
  { id: 18, base: 4, palette: 2, name: "Boy", tileset: "ui:tile.wander-look-b04", frames: { idle: [24, 25, 26, 27], walkL: [28, 29, 30, 31], walkR: [32, 33, 34, 35] }, thumb: 24 },
  { id: 19, base: 4, palette: 3, name: "Boy", tileset: "ui:tile.wander-look-b04", frames: { idle: [36, 37, 38, 39], walkL: [40, 41, 42, 43], walkR: [44, 45, 46, 47] }, thumb: 36 },
  { id: 20, base: 5, palette: 0, name: "Woman", tileset: "ui:tile.wander-look-b05", frames: { idle: [0, 1, 2, 3], walkL: [4, 5, 6, 7], walkR: [8, 9, 10, 11] }, thumb: 0 },
  { id: 21, base: 5, palette: 1, name: "Woman", tileset: "ui:tile.wander-look-b05", frames: { idle: [12, 13, 14, 15], walkL: [16, 17, 18, 19], walkR: [20, 21, 22, 23] }, thumb: 12 },
  { id: 22, base: 5, palette: 2, name: "Woman", tileset: "ui:tile.wander-look-b05", frames: { idle: [24, 25, 26, 27], walkL: [28, 29, 30, 31], walkR: [32, 33, 34, 35] }, thumb: 24 },
  { id: 23, base: 5, palette: 3, name: "Woman", tileset: "ui:tile.wander-look-b05", frames: { idle: [36, 37, 38, 39], walkL: [40, 41, 42, 43], walkR: [44, 45, 46, 47] }, thumb: 36 },
  { id: 24, base: 6, palette: 0, name: "ManGreen", tileset: "ui:tile.wander-look-b06", frames: { idle: [0, 1, 2, 3], walkL: [4, 5, 6, 7], walkR: [8, 9, 10, 11] }, thumb: 0 },
  { id: 25, base: 6, palette: 1, name: "ManGreen", tileset: "ui:tile.wander-look-b06", frames: { idle: [12, 13, 14, 15], walkL: [16, 17, 18, 19], walkR: [20, 21, 22, 23] }, thumb: 12 },
  { id: 26, base: 6, palette: 2, name: "ManGreen", tileset: "ui:tile.wander-look-b06", frames: { idle: [24, 25, 26, 27], walkL: [28, 29, 30, 31], walkR: [32, 33, 34, 35] }, thumb: 24 },
  { id: 27, base: 6, palette: 3, name: "ManGreen", tileset: "ui:tile.wander-look-b06", frames: { idle: [36, 37, 38, 39], walkL: [40, 41, 42, 43], walkR: [44, 45, 46, 47] }, thumb: 36 },
  { id: 28, base: 7, palette: 0, name: "OldMan", tileset: "ui:tile.wander-look-b07", frames: { idle: [0, 1, 2, 3], walkL: [4, 5, 6, 7], walkR: [8, 9, 10, 11] }, thumb: 0 },
  { id: 29, base: 7, palette: 1, name: "OldMan", tileset: "ui:tile.wander-look-b07", frames: { idle: [12, 13, 14, 15], walkL: [16, 17, 18, 19], walkR: [20, 21, 22, 23] }, thumb: 12 },
  { id: 30, base: 7, palette: 2, name: "OldMan", tileset: "ui:tile.wander-look-b07", frames: { idle: [24, 25, 26, 27], walkL: [28, 29, 30, 31], walkR: [32, 33, 34, 35] }, thumb: 24 },
  { id: 31, base: 7, palette: 3, name: "OldMan", tileset: "ui:tile.wander-look-b07", frames: { idle: [36, 37, 38, 39], walkL: [40, 41, 42, 43], walkR: [44, 45, 46, 47] }, thumb: 36 },
  { id: 32, base: 8, palette: 0, name: "OldMan2", tileset: "ui:tile.wander-look-b08", frames: { idle: [0, 1, 2, 3], walkL: [4, 5, 6, 7], walkR: [8, 9, 10, 11] }, thumb: 0 },
  { id: 33, base: 8, palette: 1, name: "OldMan2", tileset: "ui:tile.wander-look-b08", frames: { idle: [12, 13, 14, 15], walkL: [16, 17, 18, 19], walkR: [20, 21, 22, 23] }, thumb: 12 },
  { id: 34, base: 8, palette: 2, name: "OldMan2", tileset: "ui:tile.wander-look-b08", frames: { idle: [24, 25, 26, 27], walkL: [28, 29, 30, 31], walkR: [32, 33, 34, 35] }, thumb: 24 },
  { id: 35, base: 8, palette: 3, name: "OldMan2", tileset: "ui:tile.wander-look-b08", frames: { idle: [36, 37, 38, 39], walkL: [40, 41, 42, 43], walkR: [44, 45, 46, 47] }, thumb: 36 },
  { id: 36, base: 9, palette: 0, name: "Monk", tileset: "ui:tile.wander-look-b09", frames: { idle: [0, 1, 2, 3], walkL: [4, 5, 6, 7], walkR: [8, 9, 10, 11] }, thumb: 0 },
  { id: 37, base: 9, palette: 1, name: "Monk", tileset: "ui:tile.wander-look-b09", frames: { idle: [12, 13, 14, 15], walkL: [16, 17, 18, 19], walkR: [20, 21, 22, 23] }, thumb: 12 },
  { id: 38, base: 9, palette: 2, name: "Monk", tileset: "ui:tile.wander-look-b09", frames: { idle: [24, 25, 26, 27], walkL: [28, 29, 30, 31], walkR: [32, 33, 34, 35] }, thumb: 24 },
  { id: 39, base: 9, palette: 3, name: "Monk", tileset: "ui:tile.wander-look-b09", frames: { idle: [36, 37, 38, 39], walkL: [40, 41, 42, 43], walkR: [44, 45, 46, 47] }, thumb: 36 },
  { id: 40, base: 10, palette: 0, name: "Monk2", tileset: "ui:tile.wander-look-b10", frames: { idle: [0, 1, 2, 3], walkL: [4, 5, 6, 7], walkR: [8, 9, 10, 11] }, thumb: 0 },
  { id: 41, base: 10, palette: 1, name: "Monk2", tileset: "ui:tile.wander-look-b10", frames: { idle: [12, 13, 14, 15], walkL: [16, 17, 18, 19], walkR: [20, 21, 22, 23] }, thumb: 12 },
  { id: 42, base: 10, palette: 2, name: "Monk2", tileset: "ui:tile.wander-look-b10", frames: { idle: [24, 25, 26, 27], walkL: [28, 29, 30, 31], walkR: [32, 33, 34, 35] }, thumb: 24 },
  { id: 43, base: 10, palette: 3, name: "Monk2", tileset: "ui:tile.wander-look-b10", frames: { idle: [36, 37, 38, 39], walkL: [40, 41, 42, 43], walkR: [44, 45, 46, 47] }, thumb: 36 },
  { id: 44, base: 11, palette: 0, name: "Hunter", tileset: "ui:tile.wander-look-b11", frames: { idle: [0, 1, 2, 3], walkL: [4, 5, 6, 7], walkR: [8, 9, 10, 11] }, thumb: 0 },
  { id: 45, base: 11, palette: 1, name: "Hunter", tileset: "ui:tile.wander-look-b11", frames: { idle: [12, 13, 14, 15], walkL: [16, 17, 18, 19], walkR: [20, 21, 22, 23] }, thumb: 12 },
  { id: 46, base: 11, palette: 2, name: "Hunter", tileset: "ui:tile.wander-look-b11", frames: { idle: [24, 25, 26, 27], walkL: [28, 29, 30, 31], walkR: [32, 33, 34, 35] }, thumb: 24 },
  { id: 47, base: 11, palette: 3, name: "Hunter", tileset: "ui:tile.wander-look-b11", frames: { idle: [36, 37, 38, 39], walkL: [40, 41, 42, 43], walkR: [44, 45, 46, 47] }, thumb: 36 },
  { id: 48, base: 12, palette: 0, name: "Eskimo", tileset: "ui:tile.wander-look-b12", frames: { idle: [0, 1, 2, 3], walkL: [4, 5, 6, 7], walkR: [8, 9, 10, 11] }, thumb: 0 },
  { id: 49, base: 12, palette: 1, name: "Eskimo", tileset: "ui:tile.wander-look-b12", frames: { idle: [12, 13, 14, 15], walkL: [16, 17, 18, 19], walkR: [20, 21, 22, 23] }, thumb: 12 },
  { id: 50, base: 12, palette: 2, name: "Eskimo", tileset: "ui:tile.wander-look-b12", frames: { idle: [24, 25, 26, 27], walkL: [28, 29, 30, 31], walkR: [32, 33, 34, 35] }, thumb: 24 },
  { id: 51, base: 12, palette: 3, name: "Eskimo", tileset: "ui:tile.wander-look-b12", frames: { idle: [36, 37, 38, 39], walkL: [40, 41, 42, 43], walkR: [44, 45, 46, 47] }, thumb: 36 },
  { id: 52, base: 13, palette: 0, name: "Noble", tileset: "ui:tile.wander-look-b13", frames: { idle: [0, 1, 2, 3], walkL: [4, 5, 6, 7], walkR: [8, 9, 10, 11] }, thumb: 0 },
  { id: 53, base: 13, palette: 1, name: "Noble", tileset: "ui:tile.wander-look-b13", frames: { idle: [12, 13, 14, 15], walkL: [16, 17, 18, 19], walkR: [20, 21, 22, 23] }, thumb: 12 },
  { id: 54, base: 13, palette: 2, name: "Noble", tileset: "ui:tile.wander-look-b13", frames: { idle: [24, 25, 26, 27], walkL: [28, 29, 30, 31], walkR: [32, 33, 34, 35] }, thumb: 24 },
  { id: 55, base: 13, palette: 3, name: "Noble", tileset: "ui:tile.wander-look-b13", frames: { idle: [36, 37, 38, 39], walkL: [40, 41, 42, 43], walkR: [44, 45, 46, 47] }, thumb: 36 },
  { id: 56, base: 14, palette: 0, name: "Samurai", tileset: "ui:tile.wander-look-b14", frames: { idle: [0, 1, 2, 3], walkL: [4, 5, 6, 7], walkR: [8, 9, 10, 11] }, thumb: 0 },
  { id: 57, base: 14, palette: 1, name: "Samurai", tileset: "ui:tile.wander-look-b14", frames: { idle: [12, 13, 14, 15], walkL: [16, 17, 18, 19], walkR: [20, 21, 22, 23] }, thumb: 12 },
  { id: 58, base: 14, palette: 2, name: "Samurai", tileset: "ui:tile.wander-look-b14", frames: { idle: [24, 25, 26, 27], walkL: [28, 29, 30, 31], walkR: [32, 33, 34, 35] }, thumb: 24 },
  { id: 59, base: 14, palette: 3, name: "Samurai", tileset: "ui:tile.wander-look-b14", frames: { idle: [36, 37, 38, 39], walkL: [40, 41, 42, 43], walkR: [44, 45, 46, 47] }, thumb: 36 },
  { id: 60, base: 15, palette: 0, name: "SamuraiBlue", tileset: "ui:tile.wander-look-b15", frames: { idle: [0, 1, 2, 3], walkL: [4, 5, 6, 7], walkR: [8, 9, 10, 11] }, thumb: 0 },
  { id: 61, base: 15, palette: 1, name: "SamuraiBlue", tileset: "ui:tile.wander-look-b15", frames: { idle: [12, 13, 14, 15], walkL: [16, 17, 18, 19], walkR: [20, 21, 22, 23] }, thumb: 12 },
  { id: 62, base: 15, palette: 2, name: "SamuraiBlue", tileset: "ui:tile.wander-look-b15", frames: { idle: [24, 25, 26, 27], walkL: [28, 29, 30, 31], walkR: [32, 33, 34, 35] }, thumb: 24 },
  { id: 63, base: 15, palette: 3, name: "SamuraiBlue", tileset: "ui:tile.wander-look-b15", frames: { idle: [36, 37, 38, 39], walkL: [40, 41, 42, 43], walkR: [44, 45, 46, 47] }, thumb: 36 },
];
