// tools/wander-online-cjk-font.ts — Wander Online's name font: the common
// simplified Chinese characters a display name may use (GB 2312 level 1,
// 3755 characters), baked into the 12 px slot that draws names.
//
//   bun tools/wander-online-cjk-font.ts            # regenerate the assets
//   bun tools/wander-online-cjk-font.ts --check    # verify them, no network
//
// Writes, deterministically:
//   examples/wander-online/shared/han-level1.generated.ts  the set as deltas
//   examples/wander-online/fonts/cjk-charset.txt            the characters
//   examples/wander-online/fonts/NotoSansCJKsc-subset.otf   the subset face
//   examples/wander-online/fonts/LICENSE-NotoSansCJK.txt    OFL + notice
//   examples/wander-online/fonts/NotoSansCJKsc-subset.md    provenance
//   examples/wander-online/fonts.json                       sized fallback
//   examples/wander-online/pak.json                         license entry
//
// The source font is the pinned Noto Sans CJK SC release the Pocket RPG
// Kit's tools/lib/cjk-font.ts downloads and checksums (cache: .cache/fonts
// or $RPGKIT_FONT_CACHE). GB 2312 level 1 is derived from the encoding
// itself (rows 0xB0..0xD7), so the set needs no external list.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import {
  APP_CHARSET_FILE,
  APP_FONT_FILE,
  APP_LICENSE_FILE,
  APP_PROVENANCE_FILE,
  CJK_FONT_SOURCE,
  cjkSourceFont,
  licenseNotice,
  LICENSE_PAK_KEY,
  opentype,
  parseFontFile,
  subsetFont,
} from "../vendor/pocket-rpgkit/tools/lib/cjk-font.ts";
import { decodeHanDeltas, encodeHanDeltas } from "../examples/wander-online/shared/name-charset.ts";

export const ROOT = resolve(import.meta.dir, "..");
export const APP_DIR = join(ROOT, "examples", "wander-online");
export const GENERATED_TS = join(APP_DIR, "shared", "han-level1.generated.ts");
export const FONTS_DIR = join(APP_DIR, "fonts");
/** The font slot size names are drawn at: the HUD lines, the name tags and
 *  the first-discoverer suffix all use the 12 px regular slot. */
export const NAME_FONT_PX = 12;
export const HAN_LEVEL1_EXPECTED = 3755;

/** GB 2312 level-1 characters (rows 0xB0..0xD7), sorted by code point. */
export function gb2312Level1(): number[] {
  const decoder = new TextDecoder("gb2312", { fatal: true });
  const points = new Set<number>();
  // Level 1 is rows 0xB0..0xD7, cells 0xA1..0xFE, ending at 0xD7F9. (The
  // WHATWG "gb2312" label decodes as GBK, which maps the unassigned tail of
  // row 0xD7 into the private-use area, so the end is stated explicitly.)
  for (let row = 0xb0; row <= 0xd7; row++) {
    for (let cell = 0xa1; cell <= (row === 0xd7 ? 0xf9 : 0xfe); cell++) {
      const text = decoder.decode(new Uint8Array([row, cell]));
      const cp = text.codePointAt(0)!;
      if (text.length !== 1 || cp < 0x4e00 || cp > 0x9fa5) throw new Error(`unexpected GB 2312 mapping ${row.toString(16)}${cell.toString(16)} -> U+${cp.toString(16)}`);
      points.add(cp);
    }
  }
  const sorted = [...points].sort((a, b) => a - b);
  if (sorted.length !== HAN_LEVEL1_EXPECTED) throw new Error(`GB 2312 level 1 has ${sorted.length} characters, expected ${HAN_LEVEL1_EXPECTED}`);
  return sorted;
}

export function charsetText(codepoints: readonly number[]): string {
  const lines: string[] = [];
  for (let i = 0; i < codepoints.length; i += 64) lines.push(String.fromCodePoint(...codepoints.slice(i, i + 64)));
  return lines.join("\n") + "\n";
}

function generatedModule(codepoints: readonly number[]): string {
  return (
    "// Generated by tools/wander-online-cjk-font.ts — do not edit.\n" +
    "// GB 2312 level-1 characters as ASCII deltas from U+4E00; decode with\n" +
    "// shared/name-charset.ts. The same characters are fonts/cjk-charset.txt.\n" +
    `export const HAN_LEVEL1_COUNT = ${codepoints.length};\n` +
    `export const HAN_LEVEL1_DELTAS = ${JSON.stringify(encodeHanDeltas(codepoints))};\n`
  );
}

function provenance(count: number, fontBytes: number): string {
  return `# Noto Sans CJK SC subset (Wander Online names)

\`${APP_FONT_FILE}\` is the fallback face for the characters a Wander Online display name may
contain. \`../fonts.json\` lists it for the ${NAME_FONT_PX} px slot only (the HUD lines, name tags and the
first-discoverer suffix) and \`${APP_CHARSET_FILE}\` as a character file, so the PocketJS build bakes
every listed character into that slot from this face. \`shared/name-charset.ts\` validates names
against the same set on the client and the server.

- Source: [NotoSansCJKsc-Regular.otf](https://github.com/notofonts/noto-cjk/blob/${CJK_FONT_SOURCE.revision}/Sans/OTF/SimplifiedChinese/NotoSansCJKsc-Regular.otf)
  at commit \`${CJK_FONT_SOURCE.revision}\`.
- Source SHA-256: \`${CJK_FONT_SOURCE.sha256}\` (${CJK_FONT_SOURCE.bytes} bytes).
- Characters: ${count} (GB 2312 level 1, rows 0xB0..0xD7, derived from the encoding).
- Subset size: ${fontBytes} bytes.

Each glyph keeps the source advance width and outline; hinting and OpenType layout tables are
not carried over. Regenerate with \`bun tools/wander-online-cjk-font.ts\` (the source font is
downloaded once and cached); \`--check\` verifies the committed files without network access.

The font is licensed under the SIL Open Font License 1.1; the copyright notice and the license
text are in \`${APP_LICENSE_FILE}\`, shipped inside the app's pak as \`${LICENSE_PAK_KEY}\`. The subset is a
Modified Version under that license and is renamed "Noto Sans CJK SC Subset".
`;
}

/** The code points the committed subset face maps. */
export function subsetCoverage(fontPath = join(FONTS_DIR, APP_FONT_FILE)): Set<number> {
  const font = opentype.parse(readFileSync(fontPath).buffer.slice(0));
  const out = new Set<number>();
  for (const key of Object.keys(font.tables.cmap.glyphIndexMap)) {
    if (font.tables.cmap.glyphIndexMap[key] > 0) out.add(Number(key));
  }
  return out;
}

/** Problems with the committed assets (empty = consistent). No network. */
export function checkAssets(): string[] {
  const problems: string[] = [];
  const want = gb2312Level1();
  const generated = existsSync(GENERATED_TS) ? readFileSync(GENERATED_TS, "utf8") : "";
  const deltas = /HAN_LEVEL1_DELTAS = "([^"]*)"/.exec(generated)?.[1];
  if (!deltas) problems.push("han-level1.generated.ts is missing or malformed");
  else {
    const got = decodeHanDeltas(deltas);
    if (got.length !== want.length || got.some((cp, i) => cp !== want[i])) problems.push("han-level1.generated.ts does not encode GB 2312 level 1");
  }
  const charsetPath = join(FONTS_DIR, APP_CHARSET_FILE);
  if (!existsSync(charsetPath)) problems.push(`${APP_CHARSET_FILE} is missing`);
  else if (readFileSync(charsetPath, "utf8") !== charsetText(want)) problems.push(`${APP_CHARSET_FILE} does not list GB 2312 level 1`);
  const fontPath = join(FONTS_DIR, APP_FONT_FILE);
  if (!existsSync(fontPath)) problems.push(`${APP_FONT_FILE} is missing`);
  else {
    const covered = subsetCoverage(fontPath);
    const missing = want.filter((cp) => !covered.has(cp));
    if (missing.length) problems.push(`${APP_FONT_FILE} lacks ${missing.length} character(s), first U+${missing[0]!.toString(16)}`);
    if (covered.size !== want.length) problems.push(`${APP_FONT_FILE} maps ${covered.size} characters, expected ${want.length}`);
  }
  const manifestPath = join(APP_DIR, "fonts.json");
  if (!existsSync(manifestPath)) problems.push("fonts.json is missing");
  else {
    const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
    const fallback = manifest?.fallback?.[0];
    if (fallback?.path !== `fonts/${APP_FONT_FILE}` || JSON.stringify(fallback?.sizes) !== JSON.stringify([NAME_FONT_PX])) {
      problems.push(`fonts.json does not list fonts/${APP_FONT_FILE} for the ${NAME_FONT_PX} px slot`);
    }
    if (!manifest?.characterFiles?.includes(`fonts/${APP_CHARSET_FILE}`)) problems.push(`fonts.json does not list fonts/${APP_CHARSET_FILE}`);
  }
  if (!existsSync(join(FONTS_DIR, APP_LICENSE_FILE))) problems.push(`${APP_LICENSE_FILE} is missing`);
  const pak = existsSync(join(APP_DIR, "pak.json")) ? JSON.parse(readFileSync(join(APP_DIR, "pak.json"), "utf8")) : [];
  if (!pak.some((row: { key: string }) => row.key === LICENSE_PAK_KEY)) problems.push(`pak.json does not ship ${LICENSE_PAK_KEY}`);
  return problems;
}

export async function writeAssets(): Promise<{ characters: number; fontBytes: number }> {
  const want = gb2312Level1();
  process.env.RPGKIT_FONT_CACHE ||= join(ROOT, ".cache", "fonts");
  const source = await cjkSourceFont();
  const { bytes, missing } = subsetFont(source, want);
  if (missing.length) throw new Error(`the source font does not map ${missing.length} character(s), first U+${missing[0]!.toString(16)}`);
  mkdirSync(FONTS_DIR, { recursive: true });
  writeFileSync(GENERATED_TS, generatedModule(want));
  writeFileSync(join(FONTS_DIR, APP_CHARSET_FILE), charsetText(want));
  writeFileSync(join(FONTS_DIR, APP_FONT_FILE), bytes);
  const copyright = parseFontFile(source).getEnglishName("copyright") || "see the license below";
  writeFileSync(join(FONTS_DIR, APP_LICENSE_FILE), licenseNotice(copyright));
  writeFileSync(join(FONTS_DIR, APP_PROVENANCE_FILE), provenance(want.length, bytes.length));
  writeFileSync(
    join(APP_DIR, "fonts.json"),
    JSON.stringify({ fallback: [{ path: `fonts/${APP_FONT_FILE}`, sizes: [NAME_FONT_PX] }], characterFiles: [`fonts/${APP_CHARSET_FILE}`] }, null, 2) + "\n",
  );
  const pakPath = join(APP_DIR, "pak.json");
  const rows: Array<{ key: string; file: string }> = JSON.parse(readFileSync(pakPath, "utf8"));
  if (!rows.some((row) => row.key === LICENSE_PAK_KEY)) rows.push({ key: LICENSE_PAK_KEY, file: `fonts/${APP_LICENSE_FILE}` });
  writeFileSync(pakPath, JSON.stringify(rows, null, 2) + "\n");
  return { characters: want.length, fontBytes: bytes.length };
}

if (import.meta.main) {
  if (process.argv.includes("--check")) {
    const problems = checkAssets();
    for (const p of problems) console.error(`cjk-font: ${p}`);
    console.log(problems.length ? "cjk-font: FAIL" : "cjk-font: ok");
    process.exit(problems.length ? 1 : 0);
  } else {
    const r = await writeAssets();
    console.log(`cjk-font: ${r.characters} characters, ${r.fontBytes} font bytes`);
  }
}
