// examples/wander-online/shared/name-charset.ts — the characters a chosen
// display name may contain. The set is exactly what Wander Online bakes
// into the font slot that draws names (fonts.json beside the app entry
// lists the same characters), so every accepted name renders as glyphs,
// never as replacement boxes, on every host:
//
// - ASCII letters and digits and the separators space, "_", "." and "-"
//   (always baked; `NAME_ASCII_CHARSET` below, which is also the creation
//   grid);
// - the 3755 level-1 characters of GB 2312, the common simplified Chinese
//   set, from the app's Noto Sans CJK SC subset.
//
// The Han set is stored as ASCII deltas (`HAN_LEVEL1_DELTAS`, generated by
// tools/wander-online-cjk-font.ts) rather than as the characters themselves:
// the PocketJS build scans every string literal in the module graph for the
// atlas, and the characters belong only to the 12 px slot the manifest
// declares. The server imports this module too, so both ends refuse the
// same names.

import { HAN_LEVEL1_DELTAS, HAN_LEVEL1_COUNT } from "./han-level1.generated.ts";

/** First code point of the CJK Unified Ideographs block; deltas count from one below it. */
export const HAN_BASE = 0x4e00;
/** Variable-length base-32 digits: the first 32 symbols end a number, the
 *  next 32 continue it. No quote or backslash, so the literal stays plain. */
const DELTA_ALPHABET = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz+-";

/** Encode sorted unique code points as the delta string. */
export function encodeHanDeltas(codepoints: readonly number[]): string {
  let out = "";
  let prev = HAN_BASE - 1;
  for (const cp of codepoints) {
    let delta = cp - prev;
    if (delta <= 0) throw new RangeError("code points must be sorted, unique and at or above U+4E00");
    prev = cp;
    const digits: number[] = [];
    do {
      digits.unshift(delta & 31);
      delta >>= 5;
    } while (delta > 0);
    for (let i = 0; i < digits.length; i++) out += DELTA_ALPHABET[digits[i]! + (i === digits.length - 1 ? 0 : 32)];
  }
  return out;
}

/** Decode a delta string back to sorted code points. */
export function decodeHanDeltas(text: string): number[] {
  const out: number[] = [];
  let prev = HAN_BASE - 1;
  let acc = 0;
  for (const ch of text) {
    const v = DELTA_ALPHABET.indexOf(ch);
    if (v < 0) throw new RangeError(`bad delta symbol ${JSON.stringify(ch)}`);
    acc = acc * 32 + (v & 31);
    if (v < 32) {
      prev += acc;
      out.push(prev);
      acc = 0;
    }
  }
  if (acc !== 0) throw new RangeError("truncated delta string");
  return out;
}

let hanSet: Set<number> | null = null;

/** The level-1 Han code points, decoded once on first use. */
export function hanLevel1(): ReadonlySet<number> {
  if (!hanSet) {
    const points = decodeHanDeltas(HAN_LEVEL1_DELTAS);
    if (points.length !== HAN_LEVEL1_COUNT) throw new RangeError("the Han level-1 table is corrupt");
    hanSet = new Set(points);
  }
  return hanSet;
}

/** The level-1 Han characters as sorted text (what fonts/cjk-charset.txt holds). */
export function hanLevel1Text(): string {
  return String.fromCodePoint(...decodeHanDeltas(HAN_LEVEL1_DELTAS));
}

/** The ASCII part of the name charset, in the order the creation grid
 *  shows it: letters, digits, then the four separators (space, "_", "."
 *  and "-"). The validator and the creation grid both derive from this one
 *  string, so the grid can neither offer a character the validator refuses
 *  nor hide one it accepts. */
export const NAME_ASCII_LETTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
export const NAME_ASCII_DIGITS = "0123456789";
export const NAME_ASCII_SEPARATORS = " _.-";
export const NAME_ASCII_CHARSET = NAME_ASCII_LETTERS + NAME_ASCII_DIGITS + NAME_ASCII_SEPARATORS;

const asciiAllowed: ReadonlySet<number> = new Set(Array.from(NAME_ASCII_CHARSET, (ch) => ch.codePointAt(0)!));

/** The creation grid's typeable cells: every ASCII character a name may
 *  contain, one per cell, in `NAME_ASCII_CHARSET` order. Chinese names are
 *  typed through the web page's text box instead (a 3755-character grid
 *  would not fit a screen); desktop and PSP players can still create a
 *  Latin name here and the server accepts both. */
export function nameGridCharset(): string[] {
  return Array.from(NAME_ASCII_CHARSET);
}

/** Whether one code point may appear in a display name. */
export function nameCodePointAllowed(cp: number): boolean {
  if (cp < 0x80) return asciiAllowed.has(cp);
  return cp >= HAN_BASE && hanLevel1().has(cp);
}
